### ISSUE TITLE
didnt realise unicode was stored as hex

### ISSUE THREAD

**Issue by zupa-hu** [marriog/learning#24]
Tell me why this is wrong:
"didnt realise unicode was stored as hex"

Also, tell me how the following are stored in memory as BITS:
- "a"
- string([]byte{'b'})
- "\0x63"
- byte(100)

For example, if I asked you how uint32(1 is stored as bits, you would need to tell me:
[00000000 00000000 00000000 00000001]

I grouped to make it easier to read.

**Comment by marriog** [comment]
Tell me why this is wrong:
"didnt realise unicode was stored as hex"
 - because unicode is just the encoding type of the binary. it has nothing to do with hex. hex is just another encoding type. I should have re-worded it to "didnt realise hex was used to represent the unicode points (visualy i.e. U+004D) i can now see that unicode is shown to us as " \u{two hex digits}" but this is just our way of reading the binary better, its not stored as hex, its stored as binary. At the lowest level unicode is just binary.

Also, tell me how the following are stored in memory as BITS:

"a" - if this is a utf8 character 'a' then 97(decimal) is stored  = binary is 

"a" =                    00000000 00000000 00000000 01100001 unsigned uint32
string([]byte{'b'})=  00000000 00000000 00000000 01100010   = 62 unicode point 
"\0x63" = 'c'       =  00000000 00000000 00000000 01100011
byte(100) -       =   00000000 00000000 00000000 00000100

**Comment by zupa-hu** [comment]
I created a text file, set it to utf8 without BOM, entered a char "a", saved it, it shows 1 byte. Why?

**Comment by zupa-hu** [comment]
http://mylinks.boomla.org/files/zupa/temp/a.zip

**Comment by marriog** [comment]
utf-8 is "8" bits unlike utf-32 which is 4 bytes
so your 'a' is stored as the unicode mapped number 97 (in decimal) within the 8 bit unsigned integer

**Comment by marriog** [comment]
sorry i got the byte(100) wrong  - it was not what i had said it was
byte(100) = 'd'  = 01100100

**Comment by zupa-hu** [comment]
so if utf-8 is 8 bits then how is that file 2 bytes:
http://mylinks.boomla.org/files/zupa/temp/i.zip

Note: this one won't block you from going to func-2

**Comment by marriog** [comment]
utf8 stored your character as two bytes as it needed the room to store the code point value which is
"c3 8c" . So i was wrong - utf8 just means that if possible the encoding will ony use 8 bits, but it can use more bits when needed to store the unicode point. utf32 will always use 4 bytes no matter what (which wastes memory).

**Comment by zupa-hu** [comment]
@utf-8, yup
